# Generated by Django 3.2.5 on 2023-09-09 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SellPurchase', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donor',
            new_name='Farmer',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='donor',
            new_name='farmer',
        ),
    ]
